
spring:
  application:
    name: vtech

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vtech_store_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 36000

aws:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

security:
  public:
    post-endpoints:
      - /api/v2/users/register
      - /api/v2/login
      - /api/v2/introspect
      - /api/v2/logout
      - /api/v2/refresh
    get-endpoints:
      - /api/v2/categories/**


